### ISSUE TITLE
smartcard

### ISSUE THREAD

**Issue by duck7000** [mcdope/pam_usb#212]
### Understood

No, I'm just too lazy to provide the data you request for a bug

### Text

A simple question, is it possible to use a smartcard reader with a card and use it as auth device?

Of course I tried this but the card reader is not found while it is a usb device so i thought it might work.

**Comment by mcdope** [comment]
See very first paragraph in the README, it's answered right there

**Comment by duck7000** [comment]
Well i read the first paragraph multiple times..

There is no mention of using smartcards, but there is no mention that it don't work either. It states as long it is usb so that implies that every usb device can work

But i guess this is not going to work as you closed this issue right away

**Comment by mcdope** [comment]
Quote: "pam_usb provides hardware authentication for Linux using ordinary removable media. Tested are flash sticks and storage cards, but it should work with harddrives, SSDs and even floppies (at least USB based) too."

A smartcard is a totally different thing and not a removable media (even if I can see why one would maybe consider it to be one, since its removable, but it's not a storage media). 

Additionally it would be totally pointless because there are proper smartcard authentication modules available, so why would anyone reduce the security of a smartcard by ignoring its crypto stuff and using pam_usb instead. But like the readme says: pam_usb only works with usb media.

**Comment by duck7000** [comment]
Thank you for explaining!

Yes i thought it might work but as you explained a smartcard is different and yes it is not a common storage device.
And you are right about reduced security using it with pam_usb

So this is enough for me, usb flash drive works so i stick with that

**Comment by mcdope** [comment]
For people reaching this via google or like that: For proper smartcard authentication you can see these links

- https://ubuntu.com/server/docs/security-smart-cards
- https://wiki.archlinux.org/title/Smartcards
