### ISSUE TITLE
GNOME keyring

### ISSUE THREAD

**Issue by 13403111884** [mcdope/pam_usb#248]
### Understood

Yes, this is not a bug report / support request

### Text

What to do in the last step of automatically unlocking GNOME keyring

**Comment by mcdope** [comment]
It's all in the wiki - see https://github.com/mcdope/pam_usb/wiki/Getting-Started#auto-unlock-your-gnome-keyring

**Comment by 13403111884** [comment]
> 所有内容均在 wiki 中 - 请参阅https://github.com/mcdope/pam_usb/wiki/Getting-Started#auto-unlock-your-gnome-keyring

thank you for your reply

I already tried it and it didn't work

My system is debian12

**Comment by 13403111884** [comment]
If you still want to use it, you will have to do four things:

create .keyring_unlock_password in your home directory
in that file you put UNLOCK_PASSWORD="your_password" (including the quotes)
set permissions so only yourself (and root) can read the file by running chmod 0600 ~/.keyring_unlock_password
create an autostart entry in GNOME for /usr/bin/pamusb-keyring-unlock-gnome

It does not take effect after operation
I guess there's something wrong with the last step, but I don't know what to do.

**Comment by mcdope** [comment]
"It does not take effect after operation" still doesn't tell me the slightest bit about your issue. 

Since you mentioned "last step" previously I assume you have created an autostart entry like described here https://help.gnome.org/users/gnome-help/stable/shell-apps-auto-start.html.en for `/usr/bin/pamusb-keyring-unlock-gnome` and nonetheless it doesn't work? 

Let's go through a checklist to proceed. You did...

[ ] use GNOME
[ ] create `~/.keyring_unlock_password` AND it does contain the correct password to unlock your default keyring (by default that's usually your login password, at least on Ubuntu)
[ ] set the permissions on that file like mentioned
[ ] created an autostart entry like described in the GNOME docs (see https://help.gnome.org/users/gnome-help/stable/shell-apps-auto-start.html.en)

... and nonetheless it doesn't work for you? 

In that case: please run the command manually and paste the output here. 

Also check the system logs, I'm not sure which log exactly it uses right now but it does for sure log infos. Check syslog and auth.log - one of them should have something. 

You can see which log entries to expect at https://github.com/mcdope/pam_usb/blob/master/tools/pamusb-keyring-unlock-gnome. Every `logger` call should appear in some of your logs (if it happened :stuck_out_tongue: )

**Comment by 13403111884** [comment]
extremely grateful

I solved the problem according to your tips

**Comment by mcdope** [comment]
> extremely grateful
> 
> I solved the problem according to your tips

Glad to hear that. But what was the actual problem now? :D 

Just for the records in case some other user has the same or a similar issue...

**Comment by 13403111884** [comment]
I don't know what's supposed to be in pamusb-keyring-unlock-gnome

It solved my problem https://github.com/mcdope/pam_usb/blob/master/tools/pamusb-keyring-unlock-gnome

**Comment by mcdope** [comment]
Ooookaay.... So most likely an incomplete installation or like that. 

Closing this since solved.
