### ISSUE TITLE
Multiple devices for same user

### ISSUE THREAD

**Issue by KeyofBlueS** [mcdope/pam_usb#28]
Add same user in two or more devices isn't possible, e.g.:

```
<users>
	<user id="user">
		<device>USB_DEVICE_1</device>
	</user>
</users>
```
works fine, while:
```
<users>
	<user id="user">
		<device>USB_DEVICE_1</device>
	</user>
	<user id="user">
		<device>USB_DEVICE_2</device>
	</user>
</users>
```
will cause:
`* No authentication device configured for user "user".`

**Comment by mcdope** [comment]
Did you use two different  devices, or the same device just with different names?

**Comment by KeyofBlueS** [comment]
Different devices with different id, vendor, model, serial and volume_uuid

**Comment by mcdope** [comment]
Thanks, will investigate tomorrow.

**Comment by mcdope** [comment]
Did you happen to use earlier versions of pamusb, too? I can't remember if it was ever possible to use multiple devices. I tend to say "it's bug in the conf, shouldn't be allowed to be added in the first place".

**Comment by KeyofBlueS** [comment]
Yes I used earlier versions but never added multiple devices for same user, untill now. Anyway, searching in the original documentation i've found that it's a known issue, look [here](http://www.pamusb.org/doc/faq.html), at the end there is a question never been answered.

**Comment by mcdope** [comment]
Hmmm interesting. I was using it for years as well but never noticed it and also never checked the faq because it was already outdated when I started using pamusb.

Imho it's actually a valid use case, I would expect it to be possible to use multiple devices - esp. in case of "shared" useraccounts (think i.e of a pos terminal with a single user, but multiple ppl having an usb token for it). But then again, if it never worked... 

For now I will go with ensuring the conf tool doesn't allow this in the first place. But when done I will also open a feature ticket to implement support for multiple devices per user because it's really something that should be there if you ask me. 

But no clue when I will find time and motivation to actually implement that. Pull requests definitely welcome on that topic.
