### ISSUE TITLE
ssh_add asks for password after login

### ISSUE THREAD

**Issue by madprod** [mcdope/pam_usb#65]
Hi all,

First thank you to developers for the good work,i'm glad to be able to use pam_usb again.

I have an autorun script that executes ssh-add just after login. If i login with my password, ssh-add works as intended but if i login with the USB key (ie not typing the password) then ssh-add opens a dialog and prompts for the password.

in /var/log/auth.log there is the following message :
`sddm-helper[2576]: pam_kwallet5(sddm:session): pam_kwallet5: open_session called without kwallet5_key`

This lead me to the following askubuntu.com question (which is probably related to the original pam_usb) : https://askubuntu.com/questions/826292/sddm-pam-kwallet5-pam-usb-open-session-called-without-kwallet5-key#827127

The problem is I don't understand the answer at all and i don't want to mess with my system by blindly modifying config files.

If that matters, I am using KDE (Kubuntu 21.04) and pam_usb installed from the .deb package.

**Comment by mcdope** [comment]
That question is related yes, but not really helpful. As far as I understand that question that person had problems entering the keyring password when logging in with pamusb. But anyway, it's about some ancient version.

You will never have an auto-unlocked keyring with pamusb when your user account (or better said the keyring) was setup with a password. This is because the encryption key is derived from it, since passwordless PAM modules don't have it at runtime they can't derive the secret and provide that to the keyring.

A workaround can be to use a password-less keyring, but I wouldn't recommend that. However, the changes suggested in that question wont help - they are to disable pamusb in sddm it seems.

**Comment by mcdope** [comment]
See also
* https://bugs.launchpad.net/gnome-keyring/+bug/276384
* https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/1
(yes, those bugs are for gnome, but same thingy)
