### ISSUE TITLE
Problems after update to 0.8.0

### ISSUE THREAD

**Issue by MAlfare** [mcdope/pam_usb#91]
Hi
Used 0.73 and everything worked fine.
Installed 0.8 yesterday and have to enter password for Synaptic paket manager and "open as Admin" in Nemo since then.
Sudo works.
Using Linux Mint 20.2 Cinnamon

**Comment by mcdope** [comment]
Please provide the output of "pamusb-check --debug <yourusername>" and "w" for me to be able to help.

But most likely fixed but not released yet (#85).

**Comment by MAlfare** [comment]
Here is what you requested, plus some excerpts of Journal, where I was asked for password.file:///home/alf/PAMUSB_0.8.0_DEBUG+Journal.txt

**Comment by mcdope** [comment]
I see many "Access granted." in that log, what makes you think it fails?

**Comment by mcdope** [comment]
is mint using policykit? then you will be affected by #75 - that is fixed already, but not released yet (will become 0.8.1)

**Comment by MAlfare** [comment]
...<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Arial"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


Okt 2021
--
.. what makes you think it fails?
I am asked for password, which I did not using 0.7.3, as USB-Stick is mounted.
In a terminal sudo is O.K, but GUI-Applikations does not, as I wrote in my first message.

...is mint using policykit?
Yes, it is.
Linux Mint is built on Ubuntu 20.4 focal fossa

When will 0.8.1 be released?
If it will in the very next future, I won't go back to 0.7.3

**Comment by MAlfare** [comment]
Cannot install: libpam-usb_0.8.1_amd64.deb
"Fehler: Abhängigkeit nicht erfüllbar: libc6 (>= 2.34)"
:-(

**Comment by mcdope** [comment]
Since you seem to use a german localization I assume you speak german and will switch now... :D

Release war eigentlich für circa jetzt geplant, aber ich habe diese Woche meinen neuen PC für eine komplette Neuinstallation genutzt. Sprich ich muss mein ganzes Tooling noch einrichten und durchtesten. Denke morgen oder übermorgen. 

Was die Abhängigkeit angeht: Pech gehabt muss ich leider sagen, siehe Notes zum Milestone (https://github.com/mcdope/pam_usb/milestone/3). Das Problem ist das ich im Prinzip für jedes Ubuntu release eine VM vorhalten müsste - was zwar machbar, aber viel zu viel Aufwand ist. Ab 0.8.1 werden die vorgebauten Packages unter Ubuntu 21.10 erstellt und hängen daher auch von den entsprechenden library Versionen ab. Aber wie du dir ein eigenes deb bauen kannst, das dann auch zum System passt, ist im Wiki dokumentiert und schnell gemacht.

**Comment by MAlfare** [comment]
Tja, dann werde ich mich mit 0.7.3 begnügen.
Bin nicht so der Paketersteller / Compilierer

**Comment by mcdope** [comment]
Das ist echt fix gemacht, das längste daran ist der Download der Pakete - von denen du die meisten vermutlich eh schon drauf hast.

Ich glaube ich habe noch ne 20.04, oder zumindest 20.10, VM von alten Tests rumliegen. Wenn ich die morgen wiederfinde und die auf dem neuen PC ohne Probs booted (was sie sollte falls vorhanden) kann ich dir eins bauen, aber no promise.

**Comment by mcdope** [comment]
Hier ist ein Paket das unter 20.04 gebaut ist, das sollte bei dir installierbar sein -> https://www.dropbox.com/s/hm0fmyrurmm1t11/libpam-usb_0.8.1_amd64.deb?dl=0

**Comment by MAlfare** [comment]
Vielen Dank.
Ist installiert und funktioniert!

**Comment by mcdope** [comment]
Nice, dann mache ich die Version heute abend final und werfe sie ins Repo etc.

Wundere dich dann nicht, wird dir dann wegen Versionsnummer nicht zum update angeboten werden.
